// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxm9CfsltxxbeK4zIH00ys-3ZQcTip6TQ',
    appId: '1:563539782861:web:db22874e25a0b4bb6d4d84',
    messagingSenderId: '563539782861',
    projectId: 'adwis-2008',
    authDomain: 'adwis-2008.firebaseapp.com',
    storageBucket: 'adwis-2008.firebasestorage.app',
    measurementId: 'G-C99DPRWTFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZXA9oCVxnLnL9JVXHfm5CMF5ktNH9sD4',
    appId: '1:563539782861:android:4a793145fd194b776d4d84',
    messagingSenderId: '563539782861',
    projectId: 'adwis-2008',
    storageBucket: 'adwis-2008.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiB2aMeWpI2-54t9xI-Ui9ROsdznOywgY',
    appId: '1:563539782861:ios:c3f531491dbb18856d4d84',
    messagingSenderId: '563539782861',
    projectId: 'adwis-2008',
    storageBucket: 'adwis-2008.firebasestorage.app',
    iosBundleId: 'com.example.adwisFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiB2aMeWpI2-54t9xI-Ui9ROsdznOywgY',
    appId: '1:563539782861:ios:c3f531491dbb18856d4d84',
    messagingSenderId: '563539782861',
    projectId: 'adwis-2008',
    storageBucket: 'adwis-2008.firebasestorage.app',
    iosBundleId: 'com.example.adwisFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxm9CfsltxxbeK4zIH00ys-3ZQcTip6TQ',
    appId: '1:563539782861:web:b5dfc048c65fcb4d6d4d84',
    messagingSenderId: '563539782861',
    projectId: 'adwis-2008',
    authDomain: 'adwis-2008.firebaseapp.com',
    storageBucket: 'adwis-2008.firebasestorage.app',
    measurementId: 'G-3RV4T5H4RR',
  );
}
